### ISSUE TITLE
Error on initialization

### ISSUE THREAD

**Issue by TapsHTS** [Androz2091/multilingual-discord-bot#7]
Hi ! I have this error:
```js
const guildLanguage = guildLanguages[message.guild.id] || "english";
                              ^

ReferenceError: Cannot access 'guildLanguages' before initialization
    at Object.execute (D:\Users\legot\Visual\Lang Shop'S Version\commands\lang.js:10:31)
    at Client.<anonymous> (D:\Users\legot\Visual\Lang Shop'S Version\index.Js:22:34)
    at Client.emit (events.js:210:5)
    at MessageCreateAction.handle (D:\Users\legot\Visual\Lang Shop'S Version\node_modules\discord.js\src\client\actions\MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (D:\Users\legot\Visual\Lang Shop'S Version\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)        
    at WebSocketManager.handlePacket (D:\Users\legot\Visual\Lang Shop'S Version\node_modules\discord.js\src\client\websocket\WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (D:\Users\legot\Visual\Lang Shop'S Version\node_modules\discord.js\src\client\websocket\WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (D:\Users\legot\Visual\Lang Shop'S Version\node_modules\discord.js\src\client\websocket\WebSocketShard.js:301:10)
    at WebSocket.onMessage (D:\Users\legot\Visual\Lang Shop'S Version\node_modules\ws\lib\event-target.js:125:16)
    at WebSocket.emit (events.js:210:5)

Code: (lang.js)
const fs = require("fs");

module.exports = {
	name: 'setlang',
	description: 'Set your language!',
	usage: 'setlang english|french',
	execute(message, args, client) {


        const guildLanguage = guildLanguages[message.guild.id] || "english";
        const language = require(`./languages/${guildLanguage}`);
        const guildLanguages = require("./guilds-language.json");

        const langages = ["english", "french"]
        const newLanguageName = message.content.split(" ")[1];
        // If no new language is specified, returns an error message
        if(!newLanguageName){
            return message.channel.send(language("MISSING_LANGUAGE"));
        }
        if(!langages.includes(newLanguageName)){
            return message.channel.send(language("LANGUAGE_NO_EXIST"));
        }
        // Update our json database
        guildLanguages[message.guild.id] = newLanguageName;
        fs.writeFileSync("./guilds-language.json", JSON.stringify(guildLanguages), "utf-8");
        // Gets the new language
        const newLanguage = require(`./languages/${newLanguageName}`);
        // Send a success message
        message.channel.send(newLanguage("LANGUAGE_UPDATED"));
    },
};```

I don't understand

Thank's

**Comment by TapsHTS** [comment]
Problème trouver ! je n'avais pas mis ../ car ce n'etait pas dans la racine !
